THISPKG	= filepath
SEARCH	= -package base
EXTRA_H_FLAGS   = -H4M -K3M
EXTRA_HBC_FLAGS = -H16M -A1M

SRCS	= \
	System/FilePath/Posix.hs \
	System/FilePath/Version_0_09.hs \
	System/FilePath/Version_0_10.hs \
	System/FilePath/Version_0_11.hs \
	System/FilePath/Version_0_12.hs \
	System/FilePath/Windows.hs \
	System/FilePath.hs

# Here are the main rules.
include ../Makefile.common

# some extra rules
extra:
extracfiles:

# Here are any extra dependencies.

# C-files dependencies.

